import type { Exam } from "./types";

/**
 * Other government teaching exams (central + state), compiled from sourced
 * research (Sep 2026). These are directory-level entries: they carry accurate
 * high-level facts + the official portal, and the generic hub shows a
 * "full guide coming" page with the official link until deep content is added.
 * Every vacancy/date is provisional, verify on the official portal.
 */
export const otherExams: Exam[] = [
  {
    slug: "bihar-tre",
    name: "Bihar School Teacher (BPSC TRE 4.0)",
    shortName: "BPSC TRE",
    body: "Bihar Public Service Commission (BPSC)",
    bodyUrl: "https://bpsc.bihar.gov.in",
    region: "Bihar",
    regionShort: "Bihar",
    levels: ["Class 1–5", "Class 6–8", "Class 9–10", "Class 11–12"],
    status: "recruitment-open",
    statusLabel: "TRE 4.0: apply 25 Sep – 26 Oct 2026",
    vacancies: "32,388 total · 3,847 (Cl 1–5) · 8,563 (Cl 6–8)",
    examWindow: "Exam date not yet announced",
    summary:
      "BPSC TRE 4.0 (Advt 15/2026): 32,388 school-teacher posts. Classes 1–5 (3,847 posts) and 6–8 (8,563 posts) each sit one 150-question paper with −⅓ negative marking. Full pattern, syllabus and a day-by-day plan for both.",
    hubHref: "/exams/bihar-tre",
    planHref: "/exams/bihar-tre/plan",
    applyUrl: "https://bpsconline.bihar.gov.in/candidate/login",
    noticeUrl: "https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/Notices/Advertisement-152026-TRE-4.0_BPSC-20260922-dbsf04.pdf",
    detail: {
      lastReviewed: "24 September 2026",
      eligibilityNote:
        "From BPSC Advt 15/2026 (22 Sep 2026), which cancels Advt 14/2026. Classes 1–5: Senior Secondary (50%, or 45% under NCTE 2002 rules) + 2-year D.El.Ed (or B.El.Ed, special-education diploma, or graduation + D.El.Ed) AND CTET/BTET Paper-I. Classes 6–8: Graduation + D.El.Ed, or Graduation (50%, or 45% per NCTE) + B.Ed, among other routes, with the subject studied at graduation, AND CTET/BTET Paper-II in the same subject. Minimum age 18 on 01.08.2026; maximum age as stated in the advert (UR male 37, BC/EBC and UR female 40, SC/ST 42). Verify every point in the official advertisement.",
      ageRelaxations: [
        { category: "BC / EBC (male & female), UR female", years: "max 40" },
        { category: "SC / ST, transgender", years: "max 42" },
      ],
      posts: [
        { code: "Cl 1–5", name: "School Teacher: Primary", classes: "Classes 1–5 · 3,847 posts (General 3,065, Urdu 757, Bangla 25)", qualification: "Sr Secondary + 2-yr D.El.Ed (or equivalent routes in the advert)", tet: "CTET or BTET Paper-I", maxAge: "37–42 by category", pay: "Starting ₹25,000 + allowances" },
        { code: "Cl 6–8", name: "School Teacher: Middle", classes: "Classes 6–8 · 8,563 posts (Maths & Science 2,188, English 1,929, Sanskrit 1,225, Social Science 1,190, Hindi 1,096, Urdu 935)", qualification: "Graduation + D.El.Ed or B.Ed (subject at graduation)", tet: "CTET or BTET Paper-II (same subject)", maxAge: "37–42 by category", pay: "Starting ₹28,000 + allowances" },
      ],
      stages: [
        "Online application on BPSC's portal: 25 Sep – 26 Oct 2026 (fee ₹100; payment by 25 Oct)",
        "Objective written exam: the only selection stage (no interview)",
        "Merit: Classes 1–5 on Part II (GS); Classes 6–8 on Parts II + III. Part I (language) only needs 30%",
        "Document verification and district allotment",
      ],
      papers: [
        {
          name: "Paper 1: Classes 1–5",
          sections: [
            { name: "Part I · Language: English + Hindi/Urdu/Bangla (qualifying, min 30%)", questions: 30, marks: 30 },
            { name: "Part II · General Studies: elementary maths, mental ability, general awareness, general science, social science, Indian National Movement, geography, environment", questions: 120, marks: 120 },
          ],
          totalQuestions: 150, totalMarks: 150, durationMin: 150,
          marking: "+1 per correct answer (150 Q = 150 marks)",
          negativeMarking: "−⅓ per wrong answer; a question left completely blank is also penalised ⅓. Option E = 'not attempting' scores 0.",
          mode: "Objective, options A–E",
          note: "The split of the 120 GS questions between topics is not published. OMR vs CBT and whether the paper is bilingual are not stated in the advert. Check the admit card / exam notice.",
        },
        {
          name: "Paper 2: Classes 6–8",
          sections: [
            { name: "Part I · Language: English + Hindi/Urdu/Bangla (qualifying, min 30%)", questions: 30, marks: 30 },
            { name: "Part II · General Studies: elementary maths, general awareness, general science, Indian National Movement, geography", questions: 40, marks: 40 },
            { name: "Part III · Subject: one of Maths & Science, Social Science, Hindi, English, Sanskrit, Urdu (SCERT/NCERT level)", questions: 80, marks: 80 },
          ],
          totalQuestions: 150, totalMarks: 150, durationMin: 150,
          marking: "+1 per correct answer (150 Q = 150 marks)",
          negativeMarking: "−⅓ per wrong answer; blank also penalised ⅓. Option E = 'not attempting' scores 0.",
          mode: "Objective, options A–E",
          note: "You may choose only ONE subject, and it must be one you passed TET in. No detailed Part III topic list is given in the advert.",
        },
      ],
      syllabus: [
        { id: "lang", title: "Part I · Language (both papers, qualifying)", topics: ["Practical knowledge of English", "Practical knowledge of Hindi / Urdu / Bangla"] },
        { id: "gs1", title: "Part II · General Studies: Paper 1 (Classes 1–5)", topics: ["Elementary mathematics", "Mental ability test", "General awareness", "General science", "Social science", "Indian National Movement", "Geography", "Environment"] },
        { id: "gs2", title: "Part II · General Studies: Paper 2 (Classes 6–8)", topics: ["Elementary mathematics", "General awareness", "General science", "Indian National Movement", "Geography"] },
        { id: "sub", title: "Part III · Subject: Paper 2 (Classes 6–8)", topics: ["Mathematics & Science, Social Science, Hindi, English, Sanskrit or Urdu", "SCERT / NCERT syllabus, at the level of the minimum qualification (per the advert)"] },
      ],
      officialLinks: [
        { label: "Advertisement 15/2026 (PDF)", url: "https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/Notices/Advertisement-152026-TRE-4.0_BPSC-20260922-dbsf04.pdf", kind: "official" },
        { label: "Important notice 15/2026 (dates)", url: "https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/Notices/Important-Notice-152026-TRE-4.0-Advertisement_BPSC-20260922-vn0ekm.pdf", kind: "official" },
        { label: "District-wise vacancies: Classes 1–5", url: "https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/Notices/Districtwise-Vacancies-Class-1-to-5_BPSC-20260922-6tvh27.pdf", kind: "official" },
        { label: "District-wise vacancies: Classes 6–8", url: "https://bpsc.bihar.gov.in/wp-content/uploads/BPSC_content/Notices/Districtwise-Vacancies-Class-6-to-8_BPSC-20260922-mojyxr.pdf", kind: "official" },
        { label: "BPSC exam calendar", url: "https://bpsc.bihar.gov.in/exam-calendar/", kind: "official" },
        { label: "BPSC online application portal", url: "https://bpsconline.bihar.gov.in/candidate/login", kind: "portal" },
      ],
      mockTestIds: ["bh15-rev1"],
    },
  },
  {
    slug: "maharashtra-tait",
    name: "Maharashtra Teacher (TAIT / Pavitra)",
    shortName: "MAHA TAIT",
    body: "School Education Dept, Maharashtra (Pavitra portal)",
    bodyUrl: "https://edustaff.maharashtra.gov.in",
    region: "Maharashtra",
    regionShort: "MH",
    levels: ["Assistant Teacher", "Shikshan Sevak"],
    status: "recruitment-open",
    statusLabel: "TAIT-2025 based: preference locking",
    vacancies: "~30,209 (verify)",
    examWindow: "Merit + interview rounds",
    summary:
      "Recruitment of teachers via the Pavitra portal for MahaTAIT-2025 qualifiers. Requires MahaTET + TAIT score.",
    hubHref: "/exams/maharashtra-tait",
  },
  {
    slug: "wb-slst",
    name: "West Bengal Assistant Teacher (WBSSC SLST)",
    shortName: "WB SLST",
    body: "West Bengal School Service Commission",
    bodyUrl: "https://www.westbengalssc.com",
    region: "West Bengal",
    regionShort: "WB",
    levels: ["Class 9–10", "Class 11–12"],
    status: "notification-awaited",
    statusLabel: "Court proceedings: status volatile",
    vacancies: "~35,726 (verify; litigation)",
    summary:
      "Secondary/higher-secondary teacher recruitment (SLST). Heavily entangled in court proceedings. Status changes frequently; verify carefully before acting.",
    hubHref: "/exams/wb-slst",
  },
  {
    slug: "telangana-dsc",
    name: "Telangana Teacher (TG DSC / TRT)",
    shortName: "TG DSC",
    body: "School Education Dept, Telangana",
    bodyUrl: "https://schooledu.telangana.gov.in",
    region: "Telangana",
    regionShort: "TG",
    levels: ["SGT", "School Assistant", "Language Pandit", "PET"],
    status: "recruitment-open",
    statusLabel: "Application open (Sep 2026)",
    vacancies: "~11,062 (verify)",
    examWindow: "CBT: date TBA",
    summary:
      "Telangana District Selection Committee teacher recruitment across primary and secondary cadres. TS/AP TET or CTET carries weightage.",
    hubHref: "/exams/telangana-dsc",
  },
  {
    slug: "haryana-hssc",
    name: "Haryana TGT & PGT (HSSC / HPSC)",
    shortName: "Haryana",
    body: "Haryana Staff Selection Commission / HPSC",
    bodyUrl: "https://www.hssc.gov.in",
    region: "Haryana",
    regionShort: "HR",
    levels: ["TGT", "PGT"],
    status: "recruitment-open",
    statusLabel: "Applications closing ~Sep 2026",
    vacancies: "~8,394 TGT/PGT (verify)",
    summary:
      "Haryana secondary teacher recruitment (TGT via HSSC, PGT via HPSC). HTET/STET mandatory.",
    hubHref: "/exams/haryana-hssc",
  },
  {
    slug: "rajasthan-reet",
    name: "Rajasthan Teacher (REET + Grade III)",
    shortName: "REET",
    body: "RSSB / Board of Secondary Education, Rajasthan",
    bodyUrl: "https://rssb.rajasthan.gov.in",
    applyUrl: "https://sso.rajasthan.gov.in/signin?ru=RECRUITMENT",
    noticeUrl: "https://rpsc.rajasthan.gov.in/advertisements",
    region: "Rajasthan",
    regionShort: "RJ",
    levels: ["Level-1 (1–5)", "Level-2 (6–8)", "2nd Grade", "1st Grade"],
    status: "recruitment-open",
    statusLabel: "REET Mains (3rd Grade): results phase",
    vacancies: "~7,123 recent (verify)",
    summary:
      "REET is the state TET; the Grade III / 2nd / 1st Grade exams are the recruitment. Level-1 and Level-2 for primary and upper-primary teachers.",
    hubHref: "/exams/rajasthan-reet",
  },
  {
    slug: "dsssb",
    name: "DSSSB Teacher (Delhi)",
    shortName: "DSSSB",
    body: "Delhi Subordinate Services Selection Board",
    bodyUrl: "https://dsssb.delhi.gov.in",
    region: "Delhi",
    regionShort: "DL",
    levels: ["PRT", "TGT", "PGT", "Special Educator"],
    status: "recruitment-open",
    statusLabel: "Adv. 03/2026 cycle",
    vacancies: "~1,979 (verify)",
    summary:
      "Delhi government school teacher recruitment across PRT/TGT/PGT and special educators. CTET accepted for PRT/TGT.",
    hubHref: "/exams/dsssb",
  },
  {
    slug: "nvs",
    name: "NVS Teacher Recruitment",
    shortName: "NVS",
    body: "Navodaya Vidyalaya Samiti (via CBSE)",
    bodyUrl: "https://navodaya.gov.in",
    noticeUrl: "https://www.cbse.gov.in/cbsenew/recruitment.html",
    region: "All India",
    regionShort: "Central",
    levels: ["PGT", "TGT"],
    status: "recruitment-open",
    statusLabel: "2025–26 cycle (with KVS): results phase",
    vacancies: "~5,841 (verify)",
    summary:
      "Residential Navodaya schools. Recruited jointly with KVS via CBSE in the 2025–26 cycle. Similar pattern to KVS.",
    hubHref: "/exams/nvs",
  },
  {
    slug: "emrs",
    name: "EMRS Teacher (NESTS / ESSE)",
    shortName: "EMRS",
    body: "National Education Society for Tribal Students (NESTS)",
    bodyUrl: "https://nests.tribal.gov.in",
    noticeUrl: "https://nests.tribal.gov.in/show_content.php?lang=1&level=1&ls_id=949&lid=550",
    region: "All India",
    regionShort: "Central",
    levels: ["PGT", "TGT", "Principal"],
    status: "recruitment-open",
    statusLabel: "ESSE-2026: results phase",
    vacancies: "~7,267 (verify)",
    summary:
      "Eklavya Model Residential Schools for tribal students. Recruitment via the ESSE exam conducted for NESTS.",
    hubHref: "/exams/emrs",
  },
  {
    slug: "ap-dsc",
    name: "Andhra Pradesh Mega DSC",
    shortName: "AP DSC",
    body: "School Education Dept, Andhra Pradesh",
    bodyUrl: "https://cse.ap.gov.in",
    region: "Andhra Pradesh",
    regionShort: "AP",
    levels: ["SGT", "School Assistant", "TGT", "PGT", "PET"],
    status: "upcoming",
    statusLabel: "Notification expected ~Oct 2026",
    vacancies: "~2,535 (verify)",
    examWindow: "Exam ~Dec 2026 (expected)",
    summary:
      "Andhra Pradesh District Selection Committee mega recruitment. AP TET/CTET carries weightage in the DSC merit.",
    hubHref: "/exams/ap-dsc",
  },
  {
    slug: "mp-esb",
    name: "Madhya Pradesh Teacher (ESB Varg 1/2/3)",
    shortName: "MP ESB",
    body: "MP Employees Selection Board (ESB)",
    bodyUrl: "https://esb.mp.gov.in",
    region: "Madhya Pradesh",
    regionShort: "MP",
    levels: ["Varg-3 (Primary)", "Varg-2 (Middle)", "Varg-1 (PGT)"],
    status: "notification-awaited",
    statusLabel: "Notification expected",
    vacancies: "reported ~10,000+ (unconfirmed)",
    summary:
      "MP teacher recruitment across three 'Varg' levels via the ESB. MPTET (Varg-wise) required. Vacancy figure is speculative until notified.",
    hubHref: "/exams/mp-esb",
  },
  {
    slug: "ctet",
    name: "CTET: Central Teacher Eligibility Test",
    shortName: "CTET",
    body: "Central Board of Secondary Education (CBSE)",
    bodyUrl: "https://ctet.nic.in",
    region: "All India",
    regionShort: "Central",
    levels: ["Paper I (1–5)", "Paper II (6–8)"],
    status: "eligibility-test",
    statusLabel: "Exam 12–13 Dec 2026 (verify)",
    examWindow: "December 2026",
    summary:
      "Not a recruitment: the eligibility test that qualifies you for KVS, NVS, DSSSB and many state teaching jobs. Clear this first, then sit the recruitment exam.",
    hubHref: "/exams/ctet",
  },
  {
    slug: "utet",
    name: "UTET: Uttarakhand TET",
    shortName: "UTET",
    body: "Uttarakhand Board of School Education (UBSE)",
    bodyUrl: "https://ubse.uk.gov.in",
    region: "Uttarakhand",
    regionShort: "UK",
    levels: ["Paper I (1–5)", "Paper II (6–8)"],
    status: "eligibility-test",
    statusLabel: "Exam 29 Sep 2026 (verify)",
    examWindow: "29 Sep 2026",
    summary: "Uttarakhand's teacher eligibility test (Paper I & II): a qualifying test for teaching posts in the state.",
    hubHref: "/exams/utet",
  },
  {
    slug: "mptet",
    name: "MPTET / MSPSTET (Madhya Pradesh)",
    shortName: "MPTET",
    body: "MP Employees Selection Board (ESB)",
    bodyUrl: "https://esb.mp.gov.in",
    region: "Madhya Pradesh",
    regionShort: "MP",
    levels: ["Varg-2", "Varg-3"],
    status: "eligibility-test",
    statusLabel: "Exam 12 Oct 2026 (verify)",
    examWindow: "12 Oct 2026",
    summary: "MP teacher eligibility test for Varg-2 and Varg-3 (in-service). Precursor to the ESB Varg recruitment.",
    hubHref: "/exams/mptet",
  },
  {
    slug: "hp-tet",
    name: "HP TET: Himachal Pradesh TET",
    shortName: "HP TET",
    body: "HP Board of School Education (HPBOSE)",
    bodyUrl: "https://hpbose.org",
    region: "Himachal Pradesh",
    regionShort: "HP",
    levels: ["JBT", "TGT", "Shastri", "LT"],
    status: "eligibility-test",
    statusLabel: "Exam 22 Nov – 6 Dec 2026 (verify)",
    examWindow: "22 Nov – 6 Dec 2026",
    summary: "Himachal Pradesh teacher eligibility test across JBT/TGT/Shastri/LT categories.",
    hubHref: "/exams/hp-tet",
  },
  {
    slug: "haryana-htet",
    name: "HTET: Haryana TET",
    shortName: "HTET",
    body: "Board of School Education Haryana (BSEH)",
    bodyUrl: "https://bseh.org.in",
    region: "Haryana",
    regionShort: "HR",
    levels: ["Level 1 (PRT)", "Level 2 (TGT)", "Level 3 (PGT)"],
    status: "eligibility-test",
    statusLabel: "Exam 21–22 Nov 2026 (verify)",
    examWindow: "21–22 Nov 2026",
    summary: "Haryana teacher eligibility test (Levels 1–3). Mandatory for Haryana teaching recruitment; date has churned this cycle.",
    hubHref: "/exams/haryana-htet",
  },
  {
    slug: "jtet",
    name: "JTET: Jharkhand TET",
    shortName: "JTET",
    body: "Jharkhand Academic Council (JAC)",
    bodyUrl: "https://jac.jharkhand.gov.in",
    region: "Jharkhand",
    regionShort: "JH",
    levels: ["Paper I (1–5)", "Paper II (6–8)"],
    status: "eligibility-test",
    statusLabel: "Exam ~11 Oct 2026 (tentative)",
    examWindow: "~11 Oct 2026 (tentative)",
    summary: "Jharkhand teacher eligibility test. Qualifies you for Sahayak Acharya and other JSSC teaching recruitment.",
    hubHref: "/exams/jtet",
  },
  {
    slug: "gujarat-tat",
    name: "Gujarat TAT / HTAT (SEB)",
    shortName: "Gujarat",
    body: "State Examination Board, Gujarat",
    bodyUrl: "https://sebexam.org",
    region: "Gujarat",
    regionShort: "GJ",
    levels: ["TAT (Secondary/HS)", "HTAT (Head Teacher)"],
    status: "recruitment-open",
    statusLabel: "HTAT ~4 Oct 2026 (tentative)",
    examWindow: "HTAT ~4 Oct 2026",
    summary: "Gujarat's Teacher Aptitude Test (TAT) and Head Teacher Aptitude Test (HTAT); recruitment follows via OJAS.",
    hubHref: "/exams/gujarat-tat",
  },
  {
    slug: "tn-trb",
    name: "TN TRB & TNTET (Tamil Nadu)",
    shortName: "TN TRB",
    body: "Teachers Recruitment Board, Tamil Nadu",
    bodyUrl: "https://trb.tn.gov.in",
    region: "Tamil Nadu",
    regionShort: "TN",
    levels: ["SGT", "BT Assistant", "PG Assistant"],
    status: "upcoming",
    statusLabel: "TN TET ~Dec 2026 (tentative)",
    examWindow: "~Dec 2026 (tentative)",
    summary: "Tamil Nadu teacher recruitment (TRB) and TNTET eligibility. Dates per the TRB annual planner (tentative).",
    hubHref: "/exams/tn-trb",
  },
  {
    slug: "karnataka-kartet",
    name: "Karnataka KARTET / KREIS",
    shortName: "Karnataka",
    body: "Dept. of School Education / KEA, Karnataka",
    bodyUrl: "https://schooleducation.karnataka.gov.in",
    noticeUrl: "https://schooleducation.karnataka.gov.in/cacell/en",
    region: "Karnataka",
    regionShort: "KA",
    levels: ["Teacher", "KREIS residential"],
    status: "upcoming",
    statusLabel: "KARTET expected; KREIS in progress",
    summary: "Karnataka teacher eligibility (KARTET) and residential-school teacher recruitment (KREIS via KEA).",
    hubHref: "/exams/karnataka-kartet",
  },
];
