import type { Exam } from "./types";

/**
 * UP teacher recruitment, PRIORITY exam (written exam ~3–4 Dec 2026).
 * Conducted by UPESSC. Data compiled from sourced research (Sep 2026). Portal
 * figures are PROVISIONAL, the official UPESSC notification/syllabus PDF at
 * upessc.up.gov.in is the source of truth. The section-wise question/mark split,
 * exact vacancy count, negative-marking rate and OMR mode must be verified there.
 */
export const upExam: Exam = {
  slug: "up",
  name: "SUPER TET: UP Assistant Teacher (UPESSC)",
  shortName: "SUPER TET",
  body: "Uttar Pradesh Education Service Selection Commission (UPESSC)",
  bodyUrl: "https://upessc.up.gov.in",
  region: "Uttar Pradesh",
  regionShort: "UP",
  levels: ["Assistant Teacher", "TGT", "PGT"],
  status: "recruitment-open",
  statusLabel: "Apply by ~15 Oct · exam 3–4 Dec 2026",
  vacancies: "~12,405 Asst. Teacher / ~15,012 total (verify)",
  examWindow: "Written 3–4 Dec 2026 (verify)",
  summary:
    "The current priority on Merit Marg. UPESSC announced ~15,012 teaching posts (Sep 2026): ~12,405 primary Assistant Teacher (PRT, classes 1–5) plus TGT/PGT. Written exam in December 2026. Full pattern, UP-specific syllabus, a day-by-day plan and section-wise mocks.",
  featured: true,
  priority: true,
  hubHref: "/exams/up",
  planHref: "/exams/up/plan",
  detail: {
    lastReviewed: "21 September 2026",
    eligibilityNote:
      "Assistant Teacher (PRT, primary): Graduation + a teacher-training qualification (D.El.Ed / BTC / B.El.Ed / RCI diploma) AND a valid UPTET or CTET scorecard. UPTET/CTET are qualifying eligibility tests. You clear one first, then the recruitment written exam decides merit. Age 21–40 as on 1 July 2026. MAJOR CHANGE this cycle: selection is on the written exam alone: academic (Class 10/12/graduation) weightage has been removed for Assistant Teacher, and negative marking is newly introduced. Verify every point against the official notification.",
    ageRelaxations: [
      { category: "SC / ST / OBC (UP domicile)", years: "+5 years" },
      { category: "PwD", years: "+15 years" },
      { category: "Ex-servicemen", years: "+3 years + service" },
      { category: "Shiksha Mitra", years: "up to age 60" },
    ],
    posts: [
      {
        code: "Asst. Teacher",
        name: "Assistant Teacher (PRT): Primary",
        classes: "Classes 1–5",
        qualification: "Graduation + D.El.Ed / BTC / B.El.Ed (or RCI diploma for special education).",
        tet: "Valid UPTET or CTET Paper-I",
        maxAge: "40 (as on 1 Jul 2026)",
        pay: "Level 7 (7th CPC): verify",
      },
      {
        code: "TGT",
        name: "Trained Graduate Teacher",
        classes: "Classes 6–10 (secondary)",
        qualification: "Relevant Bachelor's + B.Ed. (per UPESSC TGT rules).",
        tet: "As specified in the notification",
        maxAge: "Verify",
      },
      {
        code: "PGT",
        name: "Post Graduate Teacher",
        classes: "Classes 11–12 (senior secondary)",
        qualification: "Relevant Master's + B.Ed. (per UPESSC PGT rules).",
        tet: "Not applicable",
        maxAge: "Verify",
      },
    ],
    stages: [
      "One-Time Registration (OTR) + online application on apply.upessc.org",
      "Written examination (OMR-based): decides merit for Assistant Teacher",
      "Document verification",
      "District / post allotment on merit → appointment",
      "Note: PGT additionally has a 40-mark interview (written 360 + interview 40 = 400).",
    ],
    papers: [
      {
        name: "Assistant Teacher (PRT): Written Exam (Primary, classes 1–5)",
        sections: [
          { name: "General Knowledge & Current Affairs (incl. UP-specific)", questions: 25, marks: 75 },
          { name: "Language: Hindi, Sanskrit & English (grammar)", questions: 30, marks: 90 },
          { name: "Mathematics", questions: 16, marks: 48 },
          { name: "Science", questions: 8, marks: 24 },
          { name: "Environmental & Social Studies", questions: 8, marks: 24 },
          { name: "Teaching Skills / Pedagogy", questions: 8, marks: 24 },
          { name: "Child Psychology / Development", questions: 8, marks: 24 },
          { name: "Logical Reasoning", questions: 5, marks: 15 },
          { name: "Information Technology (ICT)", questions: 4, marks: 12 },
          { name: "Life Skills, Management & Attitude", questions: 8, marks: 24 },
        ],
        totalQuestions: 120,
        totalMarks: 360,
        durationMin: 120,
        marking: "+3 per correct answer",
        negativeMarking: "−1 per wrong / multiple answer (newly introduced this cycle)",
        mode: "OMR / offline",
        note: "Reported section-wise split (from coaching portals): the exact per-section count is NOT yet confirmed from the official PDF. Verify on upessc.up.gov.in before relying on it. Bilingual (Hindi + English).",
      },
      {
        name: "TGT / PGT: Written Exam (Secondary)",
        sections: [
          { name: "Subject-specific (concerned subject)", questions: 90, marks: 270 },
          { name: "General Studies (incl. UP GK & current affairs)", questions: 30, marks: 90 },
        ],
        totalQuestions: 120,
        totalMarks: 360,
        durationMin: 120,
        marking: "+3 per correct answer",
        negativeMarking: "Negative marking newly introduced; rate disputed across portals (−1 vs 1/3): verify",
        mode: "OMR / offline (verify)",
        note: "Revised 2026 pattern: 90 subject + 30 General Studies. 12 TGT and 22 PGT subject syllabi are published as separate PDFs on the UPESSC portal. PGT adds a 40-mark interview.",
      },
    ],
    syllabus: [
      {
        id: "up-gk",
        title: "UP-specific General Knowledge (the differentiator)",
        topics: [
          "Administrative setup: 75 districts, 18 divisions; capital Lucknow; 8 NCR districts; largest (Lakhimpur Kheri) & smallest (Hapur) districts",
          "Rivers & water: Ganga, Yamuna, Gomti, Ghaghra, Ramganga, Betwa, Ken, Sarayu; major dams & canals",
          "Wildlife: tiger reserves (Dudhwa, Pilibhit, Amangarh, Ranipur); bird sanctuaries (Nawabganj, Okhla, Samaspur)",
          "Art & culture: Kathak (Lucknow gharana), folk dances (Nautanki, Raslila, Charkula), Chikankari, Banarasi silk, Bhadohi carpets",
          "Fairs & festivals: Kumbh / Magh Mela (Prayagraj), Ramlila, regional melas",
          "Heritage & tourism: Taj Mahal, Agra Fort, Fatehpur Sikri, Sarnath, Kushinagar, Varanasi, Ayodhya, Mathura–Vrindavan, Vindhyachal",
          "Economy & industry: ODOP; Firozabad (glass), Aligarh (locks), Moradabad (brass), Kanpur (leather), Kannauj (perfume); expressways (Purvanchal, Ganga, Yamuna, Bundelkhand)",
          "Polity: bicameral (Vidhan Sabha 403 + Vidhan Parishad); Governor, CM, first CM G.B. Pant; Allahabad HC (seat Prayagraj, bench Lucknow); 80 Lok Sabha, 31 Rajya Sabha seats",
          "History: ancient sites (Kaushambi, Sravasti); 1857 revolt centres (Meerut, Kanpur, Lucknow, Jhansi); freedom-movement figures",
          "State symbols: bird (Sarus Crane), animal (Barasingha), tree (Ashoka), flower (Palash)",
          "UP government schemes & current affairs (verify each from an official/government source)",
        ],
      },
      {
        id: "gk",
        title: "General Knowledge & Current Affairs",
        topics: [
          "Indian history: ancient (Indus, Vedic, Mauryas, Guptas), medieval (Sultanate, Mughals), modern (British rule, 1857, freedom struggle, Gandhian era)",
          "Indian & world geography: physical features, rivers, climate, soils, natural resources, agriculture",
          "Indian polity & constitution: Preamble, Fundamental Rights & Duties, DPSP, Parliament, judiciary, key amendments",
          "Indian economy: planning, budget, banking, GDP, five-year plans, poverty & development basics",
          "General science for GK: physics, chemistry, biology fundamentals; inventions & discoveries",
          "Static GK: national symbols, classical & folk dances, festivals, important days & organisations",
          "Current affairs (last 6–12 months): awards, sports, appointments, summits, books & authors",
          "Environment & ecology basics",
        ],
      },
      {
        id: "language",
        title: "Language: Hindi, Sanskrit & English",
        hindi: false,
        topics: [
          "Hindi व्याकरण: वर्ण-विचार; संज्ञा, सर्वनाम, विशेषण, क्रिया; लिंग, वचन, कारक",
          "Hindi: संधि, समास, उपसर्ग-प्रत्यय, तत्सम-तद्भव, पर्यायवाची-विलोम-अनेकार्थी",
          "Hindi: मुहावरे-लोकोक्तियाँ, अलंकार, रस, छंद, वाक्य शुद्धि, अपठित गद्यांश",
          "Sanskrit: शब्द रूप, धातु रूप, संधि, समास, कारक-विभक्ति, प्रत्यय, अनुवाद",
          "English grammar: tenses, articles, prepositions, modals, voice, narration, subject–verb agreement",
          "English vocabulary: synonyms, antonyms, one-word substitution, idioms & phrases, spelling",
          "Comprehension, error spotting, sentence rearrangement, fill in the blanks",
        ],
      },
      {
        id: "maths",
        title: "Mathematics",
        topics: [
          "Number system, LCM/HCF, simplification, fractions & decimals, surds & indices",
          "Percentage, ratio & proportion, average, partnership",
          "Profit & loss, discount, simple & compound interest",
          "Time & work, pipes & cisterns, time–speed–distance, trains, boats & streams",
          "Algebra (linear equations, polynomials); geometry (lines, angles, triangles, circles)",
          "Mensuration (area, perimeter, volume); trigonometry basics",
          "Data interpretation (tables, bar/pie/line charts); statistics (mean, median, mode)",
        ],
      },
      {
        id: "science",
        title: "Science",
        topics: [
          "Physics: motion, force, gravitation, work-energy-power, light, sound, heat, electricity, magnetism",
          "Chemistry: matter & its states, atoms & molecules, elements–compounds–mixtures, acids-bases-salts, metals & non-metals",
          "Biology: cell & tissues, plant & animal kingdom, human body systems, nutrition, diseases & prevention, reproduction",
          "Environmental science: ecosystem, natural resources, pollution, conservation, biodiversity",
          "Everyday & applied science; scientific instruments, inventions & discoveries",
        ],
      },
      {
        id: "evs-social",
        title: "Environmental & Social Studies",
        topics: [
          "Geography: solar system, earth's structure, latitudes-longitudes, continents & oceans, Indian & UP geography, maps",
          "History: major periods, the freedom struggle, national symbols",
          "Civics / Polity: Constitution, governance, local self-government, rights & duties",
          "Economics basics: needs, resources & markets",
          "Environment, community awareness, transport & road safety, disaster management",
        ],
      },
      {
        id: "pedagogy",
        title: "Teaching Skills / Pedagogy",
        topics: [
          "Meaning, nature, scope & aims of education",
          "Teaching methods & maxims; micro-teaching; core teaching skills",
          "Teaching–learning process & principles; models & approaches of teaching",
          "Educational technology & TLM (teaching-learning material)",
          "Curriculum, lesson planning, classroom management & discipline",
          "Assessment & evaluation: CCE, formative vs summative, competency-based assessment",
          "NEP 2020, NCF, RTE Act 2009; contemporary issues in education",
        ],
      },
      {
        id: "child-psych",
        title: "Child Psychology / Development",
        topics: [
          "Meaning & scope of child development & educational psychology",
          "Principles & dimensions of development: physical, cognitive, social, emotional, moral",
          "Piaget, Vygotsky, Kohlberg, Erikson; heredity vs environment",
          "Learning: theories (behaviourism, cognitivism, constructivism), transfer of learning, motivation",
          "Individual differences; intelligence & its theories; personality",
          "Adolescence: needs & problems; guidance & counselling",
          "Inclusive education, children with special needs (CWSN), learning disabilities",
        ],
      },
      {
        id: "reasoning",
        title: "Logical Reasoning",
        topics: [
          "Verbal: analogy, classification, series (number/alphabet), coding-decoding, blood relations, direction sense",
          "Ranking & ordering, syllogism, statement-conclusion, assertion & reason",
          "Puzzles, seating arrangement, data sufficiency",
          "Non-verbal: mirror & water images, paper folding & cutting, figure series, embedded figures",
          "Clocks & calendars, dice & cubes, Venn diagrams, mathematical reasoning",
        ],
      },
      {
        id: "ict",
        title: "Information Technology (ICT)",
        topics: [
          "Computer fundamentals: generations, types, hardware & software, memory & storage",
          "Operating systems; MS Office (Word, Excel, PowerPoint); file management; shortcuts",
          "Internet, email, browsers, search engines, networking basics",
          "ICT in education: digital resources, educational apps, e-content, smart classrooms",
          "Cyber safety & digital citizenship; input/output devices",
        ],
      },
      {
        id: "life-skills",
        title: "Life Skills, Management & Attitude",
        topics: [
          "Life skills: self-awareness, empathy, communication, critical & creative thinking, decision-making, problem-solving",
          "Professional ethics & values of a teacher; teacher's attitude & aptitude",
          "Teacher as facilitator, leader, mentor & counsellor; team-building",
          "Motivation; reward & punishment; classroom leadership",
          "Management: time & stress management; constitutional & human values",
        ],
      },
    ],
    strategy: [
      { title: "Weeks 1–2 · Foundation + highest weights", body: "Language grammar (Hindi/Sanskrit/English) and Maths basics. Start a daily 30-min UP-GK + current-affairs habit. Take one diagnostic full mock to set a baseline, and begin previous-year paper analysis." },
      { title: "Weeks 3–4 · Pedagogy, Child Psychology, Science, EVS", body: "These are scoring and formula-light. Add short daily Reasoning sets. 2 sectional tests/week + 1 full mock/week. Keep the UP-GK habit going." },
      { title: "Weeks 5–6 · UP-GK deep dive + ICT + Life Skills + weak-area repair", body: "Drill districts, rivers, schemes, heritage and current affairs hard. This is the differentiator. 3 full mocks; spend as long reviewing as taking each. Redo every wrong question." },
      { title: "Week 7 · Exam-condition mocks", body: "Full-length mocks every 2 days under 2-hour timing with negative marking applied. Practise OMR discipline and attempt strategy (which sections to secure first). Time the last 5 years' papers." },
      { title: "Week 8 · Taper + consolidation", body: "Alternate-day mocks, revise notes/error log and 6 months of current affairs. No new topics. Final 2 days: revision + one confidence mock. (This plan is a synthesised strategy, not an official prescription.)" },
    ],
    books: [
      { section: "All-in-one (PRT)", title: "Examcart / Arihant UP Assistant Teacher guide (latest edition)" },
      { section: "Child Development & Pedagogy", title: "Sandeep Kumar (Pearson); Arihant Experts" },
      { section: "General Hindi", title: "Lucent's Samanya Hindi; Arihant Hindi Bhasha evam Shikshashastra" },
      { section: "UP GK", title: "Drishti IAS UP Special / Lucent UP GK / Ghatna Chakra UP Special" },
      { section: "Reasoning & Quant", title: "R.S. Aggarwal (Verbal & Non-Verbal; Quantitative Aptitude)" },
      { section: "Subject (TGT/PGT)", title: "Sahitya Bhawan subject-wise TGT/PGT guides" },
    ],
    officialLinks: [
      { label: "UPESSC: official portal", url: "https://upessc.up.gov.in", kind: "official" },
      { label: "UPESSC application portal (OTR)", url: "https://apply.upessc.org", kind: "official" },
      { label: "UPTET: official", url: "https://updeled.gov.in", kind: "official" },
      { label: "CTET: official", url: "https://ctet.nic.in", kind: "official" },
    ],
    mockTestIds: ["up-mock-l1-full-1", "up-mock-l1-mixed", "up-mock-l1-gk"],
  },
};
